# Generated by Django 3.1.3 on 2020-11-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='property',
            field=models.TextField(blank=True, verbose_name='Характеристики'),
        ),
    ]
